### PR TITLE
620 tester trainer emulation

### LINKED ISSUE #620: Persons assigned the tester-trainer role and logged into the QA environment see a special drop-down menu at the top of their dashboard that allows them to select "View As" a given role, with the following possibilities to start

### PR DESCRIPTION
**Pull request by JaymeeH**
Creating emulation bar for non-production environments, and adding several roles as options to be emulated

refs #620

### CODE REVIEW

**Comment by JaymeeH** [comment]
Added dropdown menu to all non-production environments for users listed as `trainers`
Screenshot 2024-06-03 at 1 39 01 PM

**Review by carolyncole — CHANGES_REQUESTED** [review]
This seems to be dealing with the drop down menu on the user dashboard, but I do not see anything that shows who the user is currently emulating.  I do not see any change to the overall layout for the system.  This seems like a good first step toward #620, but does not fix it.

Additionally, The drop down menu should not show up in the middle of the screen as I can not get a clean view of the dashboard with it showing up where it does.  The idea is for someone to be able to snapshot the system for training.  The users will not have the dropdown menu so putting it in the middle of the screen will  mean the person taking snapshots will need to edit each one.
Screenshot 2024-06-03 at 2 33 10 PM

 I not sure you can make any additional forward progress on this ticket until #619 has been completed.  At this point the drop down menu is present, but sets nothing on the user class based on what the user selects and does not show a banner on other pages indicating which role the person is emulating.

**Comment by JaymeeH** [comment]
Finalizing the tester-trainer emulation bar. `TODO: remove the emulate button, and submit the form onChange instead`
Screenshot 2024-06-06 at 7 56 18 PM

**Review by carolyncole — APPROVED** [review]
A good step forward @JaymeeH.  Thanks!

**Pull request merged**
