### PR TITLE
Adding css styling to Tigerdata

### PR DESCRIPTION
**Pull request by JaymeeH**
styling header and footer first

### CODE REVIEW

**Comment by JaymeeH** [comment]
Styling the header/footer, dashboard, project page, and edit form.
Screenshot 2024-02-07 at 4 24 17 PM

**Comment by leefaisonr** [comment]
Bess and I deployed this to the staging server and it looks great! Big improvement, keep going on this.

**Comment by hectorcorrea** [comment]
Something looks off on the commits for this PR. How come I see some of my own commits and @jrgriffiniii and @carolyncole as part of the PR ?

**Comment by JaymeeH** [comment]
Yes, I was dealing with a flaky test, and @jrgriffiniii helped me rebase to get around it. That's why you see some other pr's and commits listed

**Review by hectorcorrea — APPROVED** [review]

**Pull request merged**
