### PR TITLE
Add an Automatic Settings section to the project show page

### LINKED ISSUE #270: Project Details page - preliminary automatic settings
### User Story
As a Data Sponsor, when I review the details of a given project, I need to see what parameters were set automatically, so I can understand what I'm able to do with the project and decide whether I need to request any changes.

### Notes
As of Dec. 13, we don't have an "Automatic Settings" section on the Project Details page (aka "show" page):
TD_ProjectDetails_AutomaticSettingsInsert_2023-12-13

The goal is to have it look like the wireframe shown in the user journey from #247, i.e.:
TD_ProjectDetails_AutomaticSettings_2023-12-13

In this preliminary phase, we are suppressing some required project metadata fields from the new project request form, but the [Standard Metadata Schema](https://docs.google.com/document/d/1XjXkzhs5ngM5cmyrmTLaIxG6TF4jT7-HMsMrjj3akRw) includes default values for 3 out of 4 that we want to include in the preliminary Project Details page: "Storage Capacity" ("500 GB"); "Storage Performance Expectations" ("Standard"); and "Project Purpose" ("Research"). The other field to display under "Automatic Settings" is "Project ID," for which #257 is meant to establish a process for automatic assignment. However, I don't think #257 needs to be a blocker for this issue; we can in the interim use placeholder values for Project IDs (e.g., 09az-0002).

I also do not want this issue to be a blocker for #287, though they are certainly related. If we can simply display all four of the automated settings on the "Project Details" page, even without including all of them in the metadata model, then I will be satisfied for now. But of course, in the future, we will need the metadata model to include all fields in the standard schema.

This issue is dependent on #264, which establishes all of the headings for the "Project Details" page

### Completion Criteria
Note there is no querying of mediaflux or tracking provenance here, ONLY taking data from a config file, saving it to the database, and displaying it on the screen

- [x] The preliminary "Project Details" page includes a section with the heading "Automatic Settings" below the "Description" section
- [x]  The "Automatic Settings" section includes 4 fields (in order): "Project ID"; "Storage Capacity"; "Storage Performance Expectations"; and "Project Purpose"
- [x] The "Project ID" value shown for a given project is the [draft DOI reserved for that project](https://github.com/pulibrary/tiger-data-app/issues/257)
- [x] Add database fields for storage_capacity_requested (string), storage_performance_expectations_requested (string), project_purpose (string)
- [x] There is a config file where these automatic values are managed
  - [x] The "Storage Capacity (Requested)" value is the default "500 GB"
  - [x] The "Storage Performance Expectations (Requested)" value is the default "Standard"
  - [x] The "Project Purpose" value is the default "Research"
- [x] The form sets these values from the default values in the config file
- [x] All of these values are displayed on the project show page

### PR DESCRIPTION
**Pull request by carolyncole**
Adds default values for the project to a configuration file
Also updates database values to have the proper requested postfix 

fixes #270

### CODE REVIEW

**Review by JaymeeH — COMMENTED** [review]
Looks good to me,

Minor UI nit:
The storage performance is misaligned in most cases.

Screenshot 2024-01-18 at 10 54 28 AM

vs what it should look like

Screenshot 2024-01-18 at 10 57 30 AM

**Review by JaymeeH — APPROVED** [review]

**Review by JaymeeH — CHANGES_REQUESTED** [review]
Looks good to me,

Minor UI nit:
The storage performance is misaligned in most cases.

Screenshot 2024-01-18 at 10 54 28 AM

vs what it should look like

Screenshot 2024-01-18 at 10 57 30 AM

**Comment by carolyncole** [comment]
@JaymeeH The issue was a css float issue.  Thanks for noticing the issue!  Should be all fixed up now.
Screenshot 2024-01-18 at 12 45 01 PM

**Review by JaymeeH — APPROVED** [review]
Looks great!

**Pull request merged**
