### PR TITLE
Refactor MediaFlux Client to utilize new Mediaflux::Http requests

### PR DESCRIPTION
**Pull request by carolyncole**
refs #116

### CODE REVIEW

**Comment by carolyncole** [comment]
@hectorcorrea it is hard to understand which parts of mediflux_client are actually being used and which parts are just copied in from the original spike.  I have converted the methods utilized by the welcome and organization list page, which encompasses many of them.  Below is a list of methods that have not been converted and will no longer work.  Can you identify which one are utilized in y our demo? 
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L44 
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L66
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L104
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L137
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L161
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L193
 * https://github.com/pulibrary/tiger-data-app/blob/4adbf476696f2a0a37f318205679af6735e95341/app/models/media_flux_client.rb#L232

**Comment by hectorcorrea** [comment]
Methods that can be removed:

```
# These were just for testing iterators
def collection_iterate
def collection_iterate_next

# These came from the original spike -- we are not really using them now
def get_content
def upload
```

Methods that we want to keep (they are called from the Project model):
```
def add_new_files_to_collection
def namespace_create
dev namespace_collection_assets
```

**Comment by hectorcorrea** [comment]
@carolyncole this looks great. I ran this branch locally and everything works except the part to display the files associated with a given project. The files are created with the "Add Test Files" (I see them in the MF Desktop) but they are not being loaded in the Project page. I'll take a closer look this afternoon on why that is.

**Comment by hectorcorrea** [comment]
@carolyncole I think the issue is in this method in the `MediaFluxClient` class. It should pass the action "get-name" for the names to come back in the response:

```
  def collection_query(collection_id, idx: 1, size: 10)
    query_request = Mediaflux::Http::QueryRequest.new(session_token: @session_id, collection: collection_id, size: size, idx: idx, action: "get-name")
    query_request.result
  end
```

**Comment by hectorcorrea** [comment]
@carolyncole that did it.

**Review by hectorcorrea — APPROVED** [review]

**Pull request merged**
